@echo off
echo EXE olusturuluyor...
echo Gerekli paketler yukleniyor...
pip install flet pyinstaller
echo Build islemi baslatildi...
flet pack main_v2.py --name "DynamicScreenBG" --icon icon.ico --add-data "locales;locales" --add-data "github.svg;." --add-data "x.svg;."
echo Islem tamamlandi. dist klasorunu kontrol edin.
pause
